// "use client";
import { Amiri } from "next/font/google";
import "./globals.css";

const amiri = Amiri({
  subsets: ["arabic"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Vision",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${amiri.className}  antialiased`}>{children}</body>
    </html>
  );
}
